### DISCUSSION TITLE
The latest Preview Version 9.0.401 throws a "targets a different processor" Error while building on Azure DevOps.

### DISCUSSION THREAD

**Discussion by DonkeyKongJr** [PrismLibrary/Prism#3102] [.NET MAUI]
Since upgrading to the latest preview Version of Prim.Maui our CI Pipeline fails with a “targets a different processor” error.

`CSC : error CS8012: Referenced assembly 'Prism.Maui, Version=9.0.401.20976, Culture=neutral, PublicKeyToken=null' targets a different processor. [/Users/runner/work/1/s/src/x/x/x.csproj::TargetFramework=net8.0-ios]`

The latest version we used worked flawlessly. However, the local debug build works as well with the latest version. Are there any known issues?

We are using the macOS-13 vmImage with XCode 15.2.

```
jobs:
  - job: Build_iOS
    displayName: Build  iOS App
    timeoutInMinutes: 120 # how long to run the job before automatically cancelling
    pool:
      vmImage: "macOS-13"
      demands:
        - MSBuild
```
